# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push: 
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Sync and Deploy
      uses: wei/git-sync@v3.0.0
      with: 
        source_repo: "vannamhh/lando-bedrock"
        source_branch: "main"
        destination_repo: "wordpress-3mm7@deploy.us1.frbit.com:wordpress-3mm7.git"
        destination_branch: "main"
        ssh_private_key: ${{ secrets.SSH_SECRET_KEY}}
        destination_ssh_private_key: ${{ secrets.SSH_SECRET_KEY }}